a = open('a.txt', 'r+')
a.write('a - 1\n')
a.write('e - 5\n')
a.close()
a = open('a.txt', 'r+')
print(a.read())
a = open('a.txt', 'r+')
a.writelines('f - 6\n')
a.close()
a = open('a.txt', 'r+')
print(a.readlines())
a.close()
